// packages/web/src/lib/components/shared/Navbar/Item.svelte
<script lang="ts">
    import { createEventDispatcher, type ComponentType } from 'svelte';

    export let icon: ComponentType;
    export let href: string;
    export let label: string;

    const dispatch = createEventDispatcher();
</script>

<!--
@component

Renders a link for the floating menu.

* Includes an icon.
-->

<li
    class="relative flex w-full items-center justify-center h-[50px]
            border-x border-t border-gray-400 first-of-type:rounded-t-md
            last-of-type:rounded-b-md last-of-type:border-b dark:border-neutral-500"
>
    <a on:click={() => dispatch('close')} {href} class="relative flex h-full w-full items-center justify-start px-5 gap-5 dark:text-neutral-100">
        <svelte:component this={icon} class="stroke-[1.5]" />
        <span>{label}</span>
    </a>
</li>

// src/components/app/shared/InsiderNav/Item.tsx

"use client";

import type { ReactNode } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";

interface ItemProps {
    icon: ReactNode;
    href: string;
}

/** Renders an icon for the navbar. */
export const Item = ({ href, icon }: ItemProps) => {
    const colors = usePathname() === href ? "bg-white text-purple-600 dark:text-blue-500" : "bg-transparent text-white";

    return (
        <Link href={href} className={`relative w-10 aspect-square rounded-md flex justify-center items-center ${colors}`}>
            {icon}
        </Link>
    )
}
