// packages/app/src/lib/components/auth/components/Input.svelte
<script lang="ts">
    export let type: 'text' | 'email' | 'password';
    export let label: string;
    export let placeholder: string;
    export let name: string;
    export let value: string;
</script>

<!--
@component

A custom controlled input field with a label on top.

* Autocomplete : Off
* Required : True
-->

<div class="relative flex w-full flex-col gap-[10px]">
    <label for={name} class="text-neutral-950">
        {label}
    </label>
    <input
        {...{ type }}
        {placeholder}
        {name}
        bind:value
        class="relative h-[50px] w-full rounded-md bg-neutral-100 text-neutral-600 px-5 text-sm"
        autoComplete="off"
        required={true}
    />
</div>

// src/app/auth/_components/Input/index.tsx

'use client';

// React
import { type Dispatch, type SetStateAction } from 'react';

// Internal
import { poppins } from '@/assets/fonts';
import styles from './index.module.scss';

interface InputProps {
  /** The type of the input. Defaults to `text`. */
  type?: "text" | "email" | "password";
  /** The label used for the input. */
  label: string;
  /** The input's placeholder. */
  placeholder: string;
  /** The controlled value. */
  value: string;
  /** The value's onChange handler. */
  setValue: Dispatch<SetStateAction<string>>;
}

/**
 * A custom controlled input field with a label on top.
 * 
 * - Autocomplete : Off
 * - Required : True
 */
export const Input = ({ type = "text", label, placeholder, value, setValue }: InputProps): JSX.Element => {
  const name = label.split(" ").join("-").toLowerCase();

  return (
    <div className={styles.field}>
      <label htmlFor={name}>{label}</label>
      <input
        type={type}
        className={`${styles.input} ${poppins.className}`}
        placeholder={placeholder}
        name={name}
        value={value}
        onChange={(event) => setValue(event.target.value)}
        autoComplete="off"
        required={true}
      />
    </div>
  )
}
