// src/components/app/shared/InsiderNav/More/Item.tsx

"use client";

import type { ReactNode } from "react";
import Link from "next/link";

interface ItemProps {
    icon: ReactNode;
    href: string;
    label: string;
    onClick: () => void;
}

/**
 * Renders a link for the main menu.
 * 
 * - Includes an icon.
 */
export const Item = ({ onClick, href, icon, label }: ItemProps) => {
    return (
        <li className="relative w-full h-[50px] flex justify-center items-center
                       border-t border-x border-gray-400 last-of-type:border-b
                       first-of-type:rounded-t-md last-of-type:rounded-b-md"
        >
            <Link onClick={onClick} href={href} className="relative w-full h-full px-5 flex justify-start items-center">
                {icon}&nbsp;&nbsp;&nbsp;&nbsp;{label}
            </Link>
        </li>
    )
}

// packages/web/src/lib/components/shared/Navbar/Item.svelte
<script lang="ts">
    import { createEventDispatcher, type ComponentType } from 'svelte';

    export let icon: ComponentType;
    export let href: string;
    export let label: string;

    const dispatch = createEventDispatcher();
</script>

<!--
@component

Renders a link for the floating menu.

* Includes an icon.
-->

<li
    class="relative flex h-[50px] w-full items-center justify-center
            border-x border-t border-gray-400 first-of-type:rounded-t-md
            last-of-type:rounded-b-md last-of-type:border-b"
>
    <a on:click={() => dispatch('close')} {href} class="relative flex h-full w-full items-center justify-start px-5 gap-5">
        <svelte:component this={icon} />
        <span>{label}</span>
    </a>
</li>
