// web/src/routes/auth/login/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import type { ActionData, PageData } from './$types';
	import { goto } from '$app/navigation';
	import AlternativeLink from '$lib/auth/AlternativeLink.svelte';
	import Input from '$lib/auth/Input.svelte';
	import Submit from '$lib/auth/Submit.svelte';

	export let data: PageData;
	export let form: ActionData;

	onMount(() => {
		document.title = 'Connexion - Silicate';

		if (data.user) {
			const shouldRedirect = window.confirm(
				`Un compte utilisant l'email ${data.user.email} est déjà connecté. Souhaitez-vous utiliser ce compte ?`
			);

			if (shouldRedirect) {
				goto('/app');
			}
		}
	});

	if (form?.missing) {
		alert('Fill all the inputs.');
	}

	if (form?.incorrect) {
		alert('The password is incorrect.');
	}

	let email: string = form?.email ?? '';
	let password: string = '';
</script>

<form method="POST" class="relative mb-5 flex w-[70%] flex-col overflow-x-hidden gap-10 px-[2px]">
	<div>
		<Input
			label="Email"
			placeholder="Entre ton email ici..."
			type="email"
			name="email"
			bind:value={email}
		/>
		<Input
			label="Mot de passe"
			placeholder="Entre ton mot de passe ici..."
			type="password"
			name="password"
			bind:value={password}
		/>
	</div>
	<Submit label="Connexion" />
</form>
<AlternativeLink text="T'as pas encore de compte ?" href="/auth/register" label="Crées-en un" />

// src/components/auth/log-in/index.tsx

"use client";

// Ract + Next
import { useState, FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import { setCookie } from 'cookies-next';

// Internal
import { verify } from '@/utils/jwt';
import { checkCredentials } from './server';
import { useToast } from '@/libs/contexts/ToastContext';

/// -- Components -- ///
import {
  AlternativeLink,
  Form,
  Header,
  Input,
  Main,
  Submit,
  Window
} from '../shared';

/** Returns the main component for the log-in page. */
export const Login = (): JSX.Element => {
  const [email, setEmail] = useState<string>("");
  const [password, setPassword] = useState<string>("");
  const router = useRouter();
  const { showToast } = useToast();

  const resetPassword = () => {
    setPassword("");
  }

  const handleOnSubmit = async (event: FormEvent) => {
    event.preventDefault();

    const jwt = await checkCredentials(email, password);

    if (!jwt) {
      showToast('Votre email ou mot de passe est incorrect.', "error");
      resetPassword();
      return;
    }

    const payload = await verify(jwt);

    setCookie("id", jwt, { maxAge: payload.exp! - payload.iat! });

    showToast('Vous êtes connecté avec succès.', "success");
    router.push('/app');
  }

  return (
    <Window>
      <Header title="Re-bienvenue sur" />
      <Main>
        <Form onSubmit={handleOnSubmit}>
          <Input type="email" label="Email" placeholder="Entre ton email ici..." value={email} setValue={setEmail} />
          <Input type="password" label="Mot de passe" placeholder="Entre ton mot de passe ici..." value={password} setValue={setPassword} />
          <Submit label="Connexion" />
        </Form>
        <AlternativeLink text="T'as pas encore de compte ?" href='/auth/sign-up' label='Crées-en un' />
      </Main>
    </Window>
  )
}
