// src/components/app/memos/Search.tsx

import SearchRoundedIcon from '@mui/icons-material/SearchRounded';
import { redirect } from "next/navigation";

interface SearchProps {
  initialValue: string
}

/**
 * Renders a search input box.
 * 
 * - Adds it as a param in the url.
 */
export const Search = async ({ initialValue }: SearchProps): Promise<JSX.Element> => {
  const handleSearch = async (formData: FormData) => {
    "use server";

    const searchValue = formData.get('search')?.toString() ?? "";

    if (searchValue === "") {
      redirect("/app/memos");
    }

    redirect(`/app/memos?search=${searchValue}`);
  }

  return (
    <form action={handleSearch} className="relative w-full h-auto flex flex-col justify-between">
      <div className="relative w-full h-[50px] rounded-lg border border-gray-400 flex justify-between">
        <input
          className="relative h-full w-[calc(100%-50px)] rounded-l-lg px-4 text-[14px]"
          type="text"
          name="search"
          placeholder="Cherche un mémo..."
          defaultValue={initialValue}
        />
        <button
          type="submit"
          className="relative h-full aspect-square flex justify-center items-center
                     after:content-[''] after:w-[1px] after:h-3/5 after:bg-gray-400
                     after:absolute after:left-0 after:top-2/5"
        >
          <SearchRoundedIcon />
        </button>
      </div>
    </form>
  )
}

// packages/web/src/lib/components/memos/Search.svelte
<script lang="ts">
    import { page } from '$app/stores';
    import IconCircleXFilled from '@tabler/icons-svelte/IconCircleXFilled.svelte';
    import IconSearch from '@tabler/icons-svelte/IconSearch.svelte';
    import { changeSearchParams } from './utils';

    const search = async () => {
        changeSearchParams('search', currentSearch, { refetchData: true });
    };

    $: undecodedCurrentSearch = $page.url.searchParams.get('search');
    $: currentSearch = undecodedCurrentSearch !== null ? decodeURI(undecodedCurrentSearch) : '';
</script>

<div role="search" class="relative w-full h-10 rounded flex justify-between items-center bg-neutral-100 text-neutral-700">
    <input
        bind:value={currentSearch}
        type="search"
        placeholder="Recherche un mémo..."
        class="relative w-[calc(100%-80px)] h-full bg-transparent px-5 rounded-l-lg text-sm"
    />
    {#if currentSearch !== ''}
        <button on:click={() => (currentSearch = '')} class="relative size-10 flex justify-center items-center">
            <IconCircleXFilled />
        </button>
    {/if}
    <button on:click={search} class="relative size-10 rounded-r-lg flex justify-center items-center search-icon">
        <IconSearch class="size-5 text-neutral-600" />
    </button>
</div>

<style>
    .search-icon::after {
        content: '';
        position: absolute;
        left: 0;
        margin: auto;
        height: 60%;
        width: 1px;
        background-color: gray;
    }
</style>
