// src/components/app/settings/Item.tsx

"use client";

import type { ReactNode } from "react";
import Link from "next/link";

interface ItemProps {
    icon: ReactNode;
    href: string;
    label: string;
    className?: string;
}

/**
 * Renders a link for the settings menu.
 * 
 * - Includes an icon.
 */
export const Item = ({ href, icon, label, className }: ItemProps) => {
    return (
        <li className={`relative w-full h-[50px] flex justify-center items-center
                       border-t border-x border-gray-400 last-of-type:border-b
                       first-of-type:rounded-t-md last-of-type:rounded-b-md ${className}`}
        >
            <Link href={href} className="relative w-full h-full px-5 flex justify-start items-center">
                {icon}&nbsp;&nbsp;&nbsp;&nbsp;{label}
            </Link>
        </li>
    )
}

// app/src/lib/components/Navbar/Item.svelte
<script lang="ts">
    import { createEventDispatcher, type ComponentType } from 'svelte';
    import { push } from "svelte-spa-router";

    export let icon: ComponentType;
    export let href: string;
    export let label: string;

    const dispatch = createEventDispatcher();
</script>

<!--
@component

Renders a link for the floating menu.

* Includes an icon.
-->

<li
    class="relative flex h-[50px] w-full items-center justify-center
            border-x border-t border-gray-400 first-of-type:rounded-t-md
            last-of-type:rounded-b-md last-of-type:border-b"
>
    <button on:click={() => dispatch('close')} on:click={() => push(href)} class="relative flex h-full w-full items-center justify-start px-5 gap-5">
        <svelte:component this={icon} />
        <span>{label}</span>
    </button>
</li>
